### ISSUE TITLE
Adding regexp expressions slows the linter by 2 secs or more

### ISSUE THREAD

**Issue by not-rusty** [GaijinEntertainment/go-exhaustruct#4]
At least that's what I've observed in my codebase with go 1.18, which is currently about 5k lines of code.

 Do you have any idea why? This is by far my favourite linter, it solves the biggest issue I have with golang.

**Comment by xobotyi** [comment]
This is weird and may be caused by complexity of your regexps.

We have a monorepo with codebase of 130k LOC, bare linter with no rexeps been running for 10 seconds, with one simple - 9.5 secs.

In future version cache for type regexp matching will be added (it reduces execution time for described codebase to 7 secs).

Ill dig into further optimisations later.

**Comment by not-rusty** [comment]
> 

Sorry, this was a low effort issue I wrote. I think it was more related to golangci-lint and other linters, running exhaustruct by itself works great.
