### ISSUE TITLE
Multiply-nested named types for structs will not be subject to enforcement

### ISSUE THREAD

**Issue by ImprintNav** [GaijinEntertainment/go-exhaustruct#66]
I noticed [here](https://github.com/GaijinEntertainment/go-exhaustruct/pull/65/files#diff-792114a42593e9a6680ea4db4707b8e9e08668a4dd215746188417ad9470f0ddR129) that the underlying type of a named type must be of type struct in order for enforcement to occur. However, this excludes named types with underlying named types with underlying struct types (and so on).

```
package main

import "fmt"

type A struct {
	X int
	Y int
}

type B A

func main() {
	fmt.Println(B{ // never enforced
		X: 5,
	})
}
```

It's not clear if this is intentional behavior. The most reasonable way to handle this from my perspective, as would be consistent with [nishanths/exhaustive](https://github.com/nishanths/exhaustive), would be to treat this the same as

```
type B  struct{
	X int
	Y int
}

func main() {
	fmt.Println(B{  // enforced based on matching rules for type B
		X: 5,
	})
}
```

**Comment by xobotyi** [comment]
It is not intentional and is a bug.

**Comment by NavneethJayendran** [comment]
@xobotyi I have a fix on [this branch](https://github.com/NavneethJayendran/go-exhaustruct/tree/resolve-66/recursively-match-wrapper-struct) that I would like to merge in for this. Could you please add me as a collaborator?

**Comment by ldez** [comment]
You don't need to be a "collaborator" to open a PR as you can see https://github.com/GaijinEntertainment/go-exhaustruct/pull/76

Click on this link: https://github.com/GaijinEntertainment/go-exhaustruct/compare/master...NavneethJayendran:go-exhaustruct:resolve-66/recursively-match-wrapper-struct
You will have a button "Create pull request".

If you don't have this button, it may be because your interactions with this repository have been limited.

**Comment by ImprintNav** [comment]
> Pull request creation failed. Validation failed: must be a collaborator

It seems that I've been singled out for... what exactly? Creating pull requests and issues in the past? There's been no pushback on any of my issues or pull requests and I've reached out to @xobotyi before. Let me do so again.

**Comment by xobotyi** [comment]
@ImprintNav i've never banned anyone, and, to be fair, do not understand where to check the rule that prevents you from creating issues\PRs.
Only collaborators (people that already have merged PR) have their PRs automaions to run without manual approval, otherwise it requires my approval or anyone from team (it is common security practice), and merge is obviously limited to team ony.

I was not able to review PRs last month due to lack of free time, but i have plans to address everything this\next week.

**Comment by ldez** [comment]
Maybe it's because 2FA is not enabled on the accounts :thinking:.
GitHub changed its policy about authentication: 2FA is required.

**Comment by xobotyi** [comment]
@ImprintNav (*types.Named).Underlying() always returns very bottom type, to matter how much times you will alias one type with another.

As you can see in #78 adding testcases without changing codebase didnt lead to broken tests.
